/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pariwisata;

/**
 *
 * @author Haris
 */
public class identitasBarang extends javax.swing.JFrame {

    /**
     * Creates new form identitasBarang
     */
    public identitasBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_teleponpenerima = new javax.swing.JTextField();
        txt_namapengirim = new javax.swing.JTextField();
        txt_alamatpengirim = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_namapenerima = new javax.swing.JTextField();
        txt_alamatpenerima = new javax.swing.JTextField();
        txt_teleponpengirim = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_tarif = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_home = new javax.swing.JButton();
        btn_bayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_teleponpenerima, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 300, 40));
        getContentPane().add(txt_namapengirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 300, 40));
        getContentPane().add(txt_alamatpengirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 300, 40));

        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 120, 40));
        getContentPane().add(txt_namapenerima, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 300, 40));
        getContentPane().add(txt_alamatpenerima, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 300, 40));
        getContentPane().add(txt_teleponpengirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 300, 40));
        getContentPane().add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 120, 40));
        getContentPane().add(txt_tarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Semester 2\\project\\UI\\MacBook Pro 14_ - 7.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btn_home.setText("jButton1");
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 60, 50));

        btn_bayar.setText("jButton2");
        getContentPane().add(btn_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 415, 130, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        new jadwalBarang().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btn_homeActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(identitasBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(identitasBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(identitasBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(identitasBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new identitasBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bayar;
    private javax.swing.JButton btn_home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_alamatpenerima;
    private javax.swing.JTextField txt_alamatpengirim;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_namapenerima;
    private javax.swing.JTextField txt_namapengirim;
    private javax.swing.JTextField txt_tarif;
    private javax.swing.JTextField txt_teleponpenerima;
    private javax.swing.JTextField txt_teleponpengirim;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
