/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pariwisata;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Haris
 */
public class jadwalBarang extends javax.swing.JFrame {
    koneksi con = new koneksi();
    /**
     * Creates new form jadwalBarang
     */
    
    private void tampil(){
        con.combo("SELECT * FROM tujuan ","id_tujuan", "tujuan", cmb_tujuan);
    }
    public jadwalBarang() {
        initComponents();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        cmb_tujuan = new javax.swing.JComboBox<>();
        cmb_sesi = new javax.swing.JComboBox<>();
        txt_sisaSheet = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 280, 40));

        cmb_tujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmb_tujuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tujuanActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_tujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 280, 40));

        cmb_sesi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sesiActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_sesi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 280, 40));

        txt_sisaSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sisaSheetActionPerformed(evt);
            }
        });
        getContentPane().add(txt_sisaSheet, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/MacBook Pro 14_ - 6.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 0, 70, 50));

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 415, 190, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       new dashboardPegawai().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new identitasBarang().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmb_tujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tujuanActionPerformed
  
        String tanggal = con.formatTanggal(jDateChooser1);
        
        if (cmb_tujuan.getSelectedItem().equals(" ")){
            //JOptionPane.showMessageDialog(this, "Kosong");
        }else{
            //JOptionPane.showMessageDialog(this, jComboBox1.getSelectedItem().toString());
            char kodeTujuan = cmb_tujuan.getSelectedItem().toString().charAt(0);
            con.combo("SELECT * FROM `jadwal_barang` WHERE `tanggal_berangkat` LIKE '"+ tanggal +"' AND `kode_tujuan` = "+ kodeTujuan, "sesi", "nopol", cmb_sesi);
        }
    }//GEN-LAST:event_cmb_tujuanActionPerformed

    private void cmb_sesiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sesiActionPerformed
          if (cmb_tujuan.getSelectedItem().equals(" ") || cmb_sesi.getSelectedItem() == null){
            //JOptionPane.showMessageDialog(this, "Kosong");
        }else{
            try {
    String url = "jdbc:mysql://localhost:3306/pariwisata";
    String user = "root";
    String password = "";
    Connection conn = DriverManager.getConnection(url, user, password);
    
    char kapasitas = cmb_sesi.getSelectedItem().toString().charAt(0);
    String sql = "SELECT * FROM `jadwal_pemesanan` WHERE `sesi` = " + kapasitas;
    Statement stmt = conn.createStatement();
    ResultSet rs = stmt.executeQuery(sql);
    
    while (rs.next()) {
  
        String sesiPilih = rs.getString("kapasitas");
        
        txt_sisaSheet.setText(sesiPilih);
        
    }
            
            
    
    rs.close();
    stmt.close();
    conn.close();
} catch (SQLException e) {

}
    }//GEN-LAST:event_cmb_sesiActionPerformed
    }
    private void txt_sisaSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sisaSheetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sisaSheetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jadwalBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jadwalBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jadwalBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jadwalBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jadwalBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_sesi;
    private javax.swing.JComboBox<String> cmb_tujuan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_sisaSheet;
    // End of variables declaration//GEN-END:variables
}
